master_server_address: 127.0.0.1:50051
local_hostname: "172.31.36.232"
metadata_server: "http://127.0.0.1:8080/metadata"
root_fs_dir: "/home/ubuntu/Udbhav/source_compile/hicache_mc"
global_segment_size: "4gb"
local_buffer_size: "4gb"
protocol: "tcp"
device_name: ""
transfer_timeout: 30
save_chunk_meta: true